// This file was automatically generated by VS extension Windows Machine Learning Code Generator VS 2017 v2.6
// from model file ArcFace.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Threading.Tasks;
using Windows.AI.MachineLearning;
using Windows.Storage.Streams;

namespace BearID
{
    public sealed class ArcFaceInput
    {
        public TensorFloat data; // shape(1,3,112,112)
    }
    
    public sealed class ArcFaceOutput
    {
        public TensorFloat fc1; // shape(1,512)
    }
    
    public sealed class ArcFaceModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<ArcFaceModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            ArcFaceModel learningModel = new ArcFaceModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<ArcFaceOutput> EvaluateAsync(ArcFaceInput input)
        {
            binding.Bind("data", input.data);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new ArcFaceOutput();
            output.fc1 = result.Outputs["fc1"] as TensorFloat;
            return output;
        }
    }
}

